### PR TITLE
check if the selection contains complete lines

### LINKED ISSUE #67: Request textDocument/rangeFormatting failed
Create a document like the following:

```r
cols <- c("a", "b", "c", "d", "e",
  "f", "g", "h", "i", "j", "k", "l",
  "m", "n", "o", "p")

cols_new <- test("file1",
  names = c(1:10, 15:20),
  colnames = c())
```

And then copy the elements of `cols` (from "a" to "p" without `c()`) and paste them into the parentheses in `colnames = c()` and an internal error of languageserver occurs:

```
internal error:  <text>:3:22: unexpected ')'
2:   "f", "g", "h", "i", "j", "k", "l",
3:   "m", "n", "o", "p"))
                        ^

[Error - 4:14:43 PM] Request textDocument/rangeFormatting failed.
  Message: <text>:3:22: unexpected ')'
2:   "f", "g", "h", "i", "j", "k", "l",
3:   "m", "n", "o", "p"))
                        ^

  Code: -32603 
```

### PR DESCRIPTION
**Pull request by randy3k**
@renkun-ken 

Does it sound too restrictive? Range formatting won't work unless the user selects carefully. Any partial highlight won't result in formatting.

close #67

### CODE REVIEW

**Comment by renkun-ken** [comment]
I'm not sure if it makes sense that we extract the specific part of the text in selection (from start line, start cursor, to end line, end cursor), format this piece text only and get new text, response to editor.

**Comment by randy3k** [comment]
It doesn't always make sense, see my example https://github.com/REditorSupport/languageserver/issues/67#issuecomment-534031336

**Comment by renkun-ken** [comment]
The latest range formatting seems to introduce a problem that 

```r
library(data.table)

```

If I range format the first line and second line (empty) together, the second line becomes `NA` 

```r
library(data.table)
NA
```

**Comment by randy3k** [comment]
I cannot reproduce it, even on VScode. On my computer, the empty line would be removed.

**Comment by randy3k** [comment]
I do notice something funny when I copy and paste a line (`cmd+c` then `cmd+v` without selection).

**Pull request merged**
