### PR TITLE
Add code action to disable linters

### PR DESCRIPTION
**Pull request by renkun-ken**
This PR enables [CodeAction](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction) and provides the following code actions:

- [x] Disable all linters for this line (appends `# nolint` in the end of the line if a linter complains).
- [ ] ~~Disable `some_linter` for this line~~
- [x] Test cases

There is an open discussion at https://github.com/jimhester/lintr/issues/720 about disabling specific linters. In the future, we could add code action to disable specific linters that produce diagnostics for certain lines. The development version of lintr already supports disabling specific linters:

```
# nolint: linter_name, linter2_name
```

```
# nolint start: linter_name, linter2_name
# nolint end
```

### CODE REVIEW

**Comment by renkun-ken** [comment]
I'd like to merge this PR to enable code actions to support only "Disable all linters for this line" before how lintr settles down how individual linters could be disabled.

**Comment by randy3k** [comment]
It makes sense to me to merge the PR. It will be great if you could come up with some tests though.

**Comment by renkun-ken** [comment]
Yes, I'm working on some test cases for this.

**Comment by renkun-ken** [comment]
Not sure why windows check not passing.

**Comment by renkun-ken** [comment]
Looks like the windows build does not use the latest pushed version since the log does not contain the diagnostics in `diagnostics_callback` with 7a27cc04fb776e2d95087eeacbff7c93d659f599.

**Comment by randy3k** [comment]
Looks like `remotes::install_local() ` was skipped because of the cache. Using `force` should fix it. 

```

Run Rscript -e "remotes::install_local()"
12
Skipping install of 'languageserver' from a local remote, the SHA1 (0.3.10) has not changed since last install.
13
  Use `force = TRUE` to force installation

```

**Comment by randy3k** [comment]
LGTM

**Pull request merged**
