### PR TITLE
make sure the path is UTF-8

### PR DESCRIPTION
**Pull request by randy3k**
it should fix some of the issues in #277.

We still need to fix the round trip issue

```
r$> a = "file:///foo/bar/中文.R"

r$> (b = languageserver:::path_from_uri(a))
[1] "/foo/bar/中文.R"

r$> (languageserver:::path_to_uri(b))
[1] "file:///foo/bar/%E4%B8%AD%E6%96%87.R"
```

### CODE REVIEW

**Comment by randy3k** [comment]
One solution is to always escape the uri from `textDocument$uri`. Say for example,

```
uri <- URLencode(textDocument$uri)
```

**Comment by renkun-ken** [comment]
Do you mean always `URLencode` the incoming URI from editor and `URLdecode` the outcoming URI to editor? I think it should work with VSCode but if an editor uses encoded URI that escapes all unicode characters, then returning a decoded URI seems undesired by such editors?

**Comment by renkun-ken** [comment]
I don't know what other editors do but VSCode seems to only encode a minimal set of reserved characters. For example, on macOS:

```
测试 copy !$&'()*+,;=:?@#.R
```

becomes

```
测试%20copy%20!$&%27()*+,;=:%3F@%23.R
```

**Comment by randy3k** [comment]
>  `URLdecode` the outcoming URI to editor? 
No. We still need to escape special characters like spaces.

But it raises another issue, would vscode understands both `"测试%20copy%20!$&%27()*+,;=:%3F@%23.R"` and `"%E6%B5%8B%E8%AF%95%20copy%20!$&'()*+,;=:?@#.R"`?

**Comment by randy3k** [comment]
Oops, 

I just notice that vscode escapes `'` but R does not so `URLencode` might not work.

**Comment by renkun-ken** [comment]
I tried the latest commit in this PR and I don't observe any problem working with `测试 copy !$&'()*+,;=:?@#.R`.

**Comment by renkun-ken** [comment]
Always encoding incoming URIs and not decoding outcoming URIs assumes the editor always does decoding, which I think is quite a safe assumption.

**Comment by randy3k** [comment]
It also fixes #279 (but I don't understand why).

**Comment by renkun-ken** [comment]
Thanks for working on this. LGTM.

**Pull request merged**
