### PR TITLE
improve the search functions

### PR DESCRIPTION
**Pull request by randy3k**

### CODE REVIEW

**Comment by renkun-ken** [comment]
This PR does not seem to work for me. Signature and argument completion no longer show.

**Comment by renkun-ken** [comment]
For the following source code

```r
mean(
```

I add some logging to show `result$token` in `signature_reply`, and it got empty string.

```
signature_reply 1 {"line":0,"character":5}

signature_reply 2 {"token":""}
```

**Comment by randy3k** [comment]
Let me check it again. I assumed it was okay because all the tests passed.

**Comment by randy3k** [comment]
It is working fine on my machine. Could you try again the current master?

**Comment by renkun-ken** [comment]
I tried `rm -rf src/*.*o` and clean reinstall but still does not work, either on macOS and Ubuntu remote.

**Comment by randy3k** [comment]
I ran `pkgbuild::clean_dll()` and install again. And now I could reproduce the error.

**Comment by randy3k** [comment]
You might want to revert this PR in your local installation for the moment.

**Comment by randy3k** [comment]
144cf71 should fix it. Thank for the tests.

**Comment by renkun-ken** [comment]
It works! Thanks for the quick fix!

**Comment by renkun-ken** [comment]
Not sure why tests passed, maybe this is not fully covered?

**Comment by randy3k** [comment]
Yup, there are some edge cases.

**Pull request merged**
