### PR TITLE
Make to_string() more robust

### PR DESCRIPTION
**Pull request by renkun-ken**
The elements of `dots` can be anything. This PR makes it more robust.

### CODE REVIEW

**Comment by randy3k** [comment]
What's the issue of `vapply` here?

**Comment by renkun-ken** [comment]
When I modify a file and save, the language server will crash with the following logging:

```
Error in vapply(dots, function(x) { : values must be length 1,
 but FUN(X[[2]]) result is length 0




exiting

Warning messages:
1: In readChar(self$inputcon, n, useBytes = TRUE) :
  text connection used with readChar(), results may be incorrect
2: In readChar(self$inputcon, n, useBytes = TRUE) :
  text connection used with readChar(), results may be incorrect
3: In readChar(self$inputcon, n, useBytes = TRUE) :
  text connection used with readChar(), results may be incorrect
4: In readChar(self$inputcon, n, useBytes = TRUE) :
  text connection used with readChar(), results may be incorrect
5: In readChar(self$inputcon, n, useBytes = TRUE) :
  text connection used with readChar(), results may be incorrect

[Error - 1:46:19 PM] Connection to server got closed. Server will not be restarted.
Language server exited with exit code 0
```

It looks like some complex objects are passed to `to_string()`. And I debug it is caused by an object like this:

```
!!! to_string: 
 Classes 'Namespace', 'R6' <Namespace>   Public:     clone: function (deep = FALSE)      exists: function (objname)      exports: hour shift is.data.table dcast.data.table rleid chgroup  ...     functs: hour shift is.data.table dcast.data.table rleid chgroup  ...     get_formals: function (funct)      get_signature: function (funct)      initialize: function (pkgname)      nonfuncts: .GRP .__C__data.table .BY .I .N .EACHI .__C__IDate .__C_ ...     package_name: data.table     print: function ()      unexports: aggregate_funs all.equal.data.table any_na anyDuplicated ...  


!!! to_string: 
  'try-error' chr "Error in vapply(dots, function(x) { : values must be length 1,\n but FUN(X[[2]]) result is length 0\n"  - attr(*, "condition")=List of 2   ..$ message: chr "values must be length 1,\n but FUN(X[[2]]) result is length 0"   ..$ call   : language vapply(dots, function(x) {     cat("!!! to_string: \n", capture.output(str(x)), "\n\n\n", file = "~/debug.log",  ...   ..- attr(*, "class")= chr [1:3] "simpleError" "error" "condition" 
```

**Comment by randy3k** [comment]
I think we will need to rebase your branch.

**Comment by renkun-ken** [comment]
I can start a new branch on the latest master with this function updated.

**Pull request closed without merging**
