### PR TITLE
make sure NULL converts to json's null

### LINKED ISSUE #192: lsp-mode hangs with ess-r-mode: potential issues with languageserver
This issues was originally posted at https://github.com/emacs-lsp/lsp-mode/issues/1383 and has the error log generated by `lsp-mode` associated with the issue.

I was advised to post the issue here as it seems to be a problem with `languageserver` and not the Emacs `lsp-mode` package. 

Please let me know if you need any further information.

### PR DESCRIPTION
**Pull request by randy3k**
close #192

### CODE REVIEW

**Comment by randy3k** [comment]
The failures of macOS builds are irrelevant.

**Comment by renkun-ken** [comment]
May I ask if returning `NULL` is sufficient for both cases (dict object expecting `{...}` and array object expecting `[...]`)?

**Comment by randy3k** [comment]
I checked the lsp specification, almost all replies' results also accept `null`. So it should not be a problem.

**Comment by renkun-ken** [comment]
LGTM

**Pull request merged**
