### PR TITLE
docker container for development

### PR DESCRIPTION
**Pull request by kforner**
I added a Makefile and a Dockerfile to streamline the development, in particular the testing. 
Cf DEV.md
Basically, if you have docker installed, you just build the docker, then run the tests with `make docker/tests` even if you do not have R installed. 
We can easily extend it to test on multiple R versions. 

If you are interested, my next contributions will be to setup continuous integration with Travis. 
Then the test coverage. 
And then I'll start adding some tests to get a grip on the package implementation.

### CODE REVIEW

**Comment by kforner** [comment]
Oh I just realized that the Travis CI is already setup. Good!

**Comment by kforner** [comment]
P.S:
I borrowed the docker test system from my package: https://github.com/kforner/rcpp_progress

**Comment by kforner** [comment]
Hi, Should I wait ? 
I had in mind to do some merge requests iteratively, but at this rate this will take forever.  Should I continue working on my side in the meantime ?

**Comment by randy3k** [comment]
Sorry for the late reply. I am extremely busy these days to review it. This PR should not affect your features related PRs.

**Comment by randy3k** [comment]
This PR is outdated. Let's close it for now. Also, I am not sure if we need to include the docker file here.

**Pull request closed without merging**
