### PR TITLE
Use more effecient methods to construct completions

### PR DESCRIPTION
**Pull request by renkun-ken**
1. Use `startsWith` in vectorized way and `lapply` for higher efficiency
2. Fix error when typing `for (i` in editor which causes the following error:

```
[Error - 11:12:35 PM] Request textDocument/completion failed.
  Message: non-character object(s)startsWith(names(args), token)

  Code: -32603 
```

### CODE REVIEW

**Comment by randy3k** [comment]
thanks. it seems reasonable. will pull and test it later.

**Comment by randy3k** [comment]
hey @renkun-ken,
are you interested to be a member of REditorSupport?

**Comment by renkun-ken** [comment]
Sure! I'm trying to work with vscode but I'm not familiar with how LSP works and how to correctly debug the package at the moment. Will read the LSP docs and more of the code later.

**Comment by randy3k** [comment]
Welcome to our team. I am glad that there are more contributors. Unfortunately, I personally do not use VSCode and don't know much how to debug it.

I would be happy to assist future contributors on Atom, Sublime Text or Neovim though.

**Pull request merged**
