### PR TITLE
Fix hover func arg

### LINKED ISSUE #345: Hover on symbol in a function with functional argument causes parse error
```r
test <- function(var1 = 0,
  var2 = function(x) length(x) == 0) {
  var2
}
```

Hover on `var2` in the function body, the following error occurs:

```
internal error: Error: <text>:1:37: unexpected ')'
1: function(result) length(result) == 0)
                                        ^
Call: parse(text = func_text, keep.source = FALSE)
Stack trace:
1: parse(text = func_text, keep.source = FALSE)
2: hover_reply(id, uri, self$workspace, document, point)
3: self$deliver(hover_reply(id, uri, self$workspace, document, point))
4: dispatch(self, id, params)
```

### PR DESCRIPTION
**Pull request by renkun-ken**
Close #345 

This PR fixes the XPath to find if the last definition is a function and adds some test cases.

### CODE REVIEW

**Comment by randy3k** [comment]
It seems some strange things are going in the tests.

**Comment by renkun-ken** [comment]
Looks like something is working properly in CI runners recently.

**Comment by renkun-ken** [comment]
All tests of my open PRs are working locally though.

**Comment by randy3k** [comment]
Thank you for confirming it. I really want to fix the CI issues first.

**Comment by renkun-ken** [comment]
Sure. I'll take a look too when I could.

**Review by randy3k — APPROVED** [review]

**Pull request merged**
