### PR TITLE
Respect linter_file in diagnostics

### LINKED ISSUE #235: .lintr defaults are not respected
I have a `.lintr` file in my repo root and running `lintr::lint_package()` works fine.

However, the disabled linters are not honored from languageserver and still appear in the problems pane.

`.lintr`

```
linters: with_defaults(assignment_linter = NULL, object_name_linter = NULL)
```

### PR DESCRIPTION
**Pull request by renkun-ken**
Closes #235

### CODE REVIEW

**Comment by randy3k** [comment]
Thanks

**Comment by randy3k** [comment]
Maybe it's time for another release?

**Comment by renkun-ken** [comment]
Sounds good.

**Comment by randy3k** [comment]
Due to https://github.com/REditorSupport/languageserver/issues/235#issuecomment-601632219,
I will pause the submission fir the moment.

**Comment by renkun-ken** [comment]
#235 is resolved so we can continue.

**Pull request merged**
