### PR TITLE
add symbols

### LINKED ISSUE #46: Symbols
I realised that the machinery for Go to Definition can also be used to provide symbol information (e.g., for outlines and Go to Symbol).

I have a working implementation for `textDocument/documentSymbol`, although it still needs cleaning up. I should be able to put together a PR in the next week or so.

### PR DESCRIPTION
**Pull request by andycraig**
Closes #46 

This PR adds handlers for `textDocument/documentSymbol` and `workspace/symbol`. The symbols supported are the same as those for Go to Definition, which at present is functions only.

The video below shows how these are used in Visual Studio Code. 'Go to Symbol in File...' uses `textDocument/documentSymbol`, and 'Go to Symbol in Workspace...' uses `workspace/symbol`. The Outline section at the bottom left and the 'breadcrumbs' section just below the file names also use `textDocument/documentSymbol`.

symbols

### CODE REVIEW

**Comment by randy3k** [comment]
Wow, excellent. I will take a look this weekend and merge it asap.

**Comment by randy3k** [comment]
@andycraig Thanks again for your contributions. I have just sent you an invitation for joining the organization and I should have done it much earlier.

**Comment by andycraig** [comment]
@randy3k Great, thank you very much and very happy to join!

**Comment by randy3k** [comment]
Merged. I will tag a release soon.

**Comment by andycraig** [comment]
Great, thank you!

**Pull request merged**
