### PR TITLE
make sure column is defined

### LINKED ISSUE #609: Error in Neovim: “attempt to compare string with number”
Based on the error stack traceback, this is related to #481. Unfortunately #565 did not fix it, and the error persists in the current HEAD revision (adc2189eff742fec42f3ece6df5c3c33062607b3).

To reproduce the issue, create a file containing the following and open it in Neovim with LSP configured to use ‘languageserver’:

```r
a =
b = 2
```

Here’s the full error message:

```
Error executing vim.schedule lua callback: /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:431: attempt to compare string with number
stack traceback:
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:431: in function 'add'
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:468: in function 'get_diagnostics'
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:1162: in function 'show'
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:724: in function 'set'
        /opt/local/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:206: in function 'handler'
        /opt/local/share/nvim/runtime/lua/vim/lsp.lua:1049: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### PR DESCRIPTION
**Pull request by randy3k**
an attempt to fix #609

### CODE REVIEW

**Review by renkun-ken — APPROVED** [review]
LGTM

**Comment by randy3k** [comment]
Let wait and see if @klmr could confirm that it fixes the issue.

**Comment by klmr** [comment]
Unfortunately this does *not* fix the issue. And when logging the value of `column` I can see that it is `-1` with the minimal test case from #609.

Of course the code could simply be modified to test for values ≤ 0 but maybe we should figure out why the value is negative in the first place. This seems to come directly from `lintr::lint`, correct?

**Comment by randy3k** [comment]
In this case, the bug is actually triggered by `code_point_to_unit` which assumes that offset is always >=0. Hopefully it will fix the issue.

**Comment by klmr** [comment]
Hallelujah, I think that fixes it. And it even returns the correct (rather than just an arbitrary) position for the diagnostic to the language client, I believe.

**Comment by randy3k** [comment]
Great, let's merge it.

**Pull request merged**
