### PR TITLE
Update services

### PR DESCRIPTION
**Pull request by renkun-ken**
This PR adds foldingRangeProvider and selectionRangeProvider to README and selectionRange handler function.

### CODE REVIEW

**Comment by randy3k** [comment]
Awesome. Mind writing some functional tests for the new providers?

**Comment by renkun-ken** [comment]
Since the two providers are not implemented, In addition to the respond functions, is there anything I should add?

**Comment by randy3k** [comment]
Oh, I misread the title. I thought that you have already implemented them. 😅

**Comment by renkun-ken** [comment]
Still some issues about foldingRangeProvider and selectionRangeProvider, or otherwise this PR should include the implementation. 😂

**Pull request merged**
