### PR TITLE
Provide signature for primitive functions

### PR DESCRIPTION
**Pull request by renkun-ken**
Since primitive functions do have `args()` output, we can provide their signature.

### CODE REVIEW

**Comment by randy3k** [comment]
I forget why I put the check there, maybe because most primitive functions only have one argument.

**Comment by renkun-ken** [comment]
Primitive functions like `sum`, `max` also have `na.rm=` argument. Since there are no formals for them, providing signature and documentation will help.

**Comment by randy3k** [comment]
> Since there are no formals for them
it sounds familiar, it may be the reason I put this check here while I was working on `get_formals`. This PR LGTM.

**Comment by renkun-ken** [comment]
Thanks!

**Pull request merged**
