### PR TITLE
bump to 0.3.10

### PR DESCRIPTION
**Pull request by randy3k**
TODO:

- [x] update NEWS
- [x] final touchup
- [x] submit to CRAN

### CODE REVIEW

**Comment by renkun-ken** [comment]
I think the new release should include the latest commit then.

**Comment by randy3k** [comment]
Just submitted to CRAN.

**Comment by randy3k** [comment]
@renkun-ken 
Just saw another macOS failure at https://github.com/REditorSupport/languageserver/runs/2377902109#step:5:136
Something fishy is going on.

**Comment by randy3k** [comment]
I think I have figured outt the reason. The full path is
```
source("/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpe5QjIW/working_dir/Rtmp0hI9cO/file8806c53b4cc.R")
```
When we do `textDocument/definition`, somehow it returns  the var as in`/var/folders..` instead of the whole path.

This is the detail of the log found in the [Artifacts](https://github.com/REditorSupport/languageserver/actions/runs/762463588)
<details>

[2021-04-19 05:52:25.081] session:  {
  "pid": 4569,
  "wd": "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmp0SQM6a/file611633eb7d3/languageserver.Rcheck/tests/testthat",
  "args": ["/Library/Frameworks/R.framework/Resources/bin/exec/R", "--slave", "-e", "languageserver::run(debug~+~=~+~'/private/tmp/languageserver/macos-log')"],
  "env": {
    "__CF_USER_TEXT_ENCODING": "0x1F5:0:0",
    "_R_CHECK_BASHISMS_": "TRUE",
    "_R_CHECK_CODE_USAGE_VIA_NAMESPACES_": "TRUE",
    "_R_CHECK_CODE_USAGE_WITH_ONLY_BASE_ATTACHED_": "TRUE",
    "_R_CHECK_CODOC_VARIABLES_IN_USAGES_": "TRUE",
    "_R_CHECK_COMPILATION_FLAGS_": "TRUE",
    "_R_CHECK_CONNECTIONS_LEFT_OPEN_": "TRUE",
    "_R_CHECK_DATALIST_": "TRUE",
    "_R_CHECK_DEPENDS_ONLY_DATA_": "TRUE",
    "_R_CHECK_DOT_FIRSTLIB_": "TRUE",
    "_R_CHECK_EXCESSIVE_IMPORTS_": "20",
    "_R_CHECK_FUTURE_FILE_TIMESTAMPS_": "TRUE",
    "_R_CHECK_INSTALL_DEPENDS_": "TRUE",
    "_R_CHECK_INTERNALS2_": "1",
    "_R_CHECK_LENGTH_1_CONDITION_": "package:_R_CHECK_PACKAGE_NAME_,verbose",
    "_R_CHECK_LENGTH_1_LOGIC2_": "package:_R_CHECK_PACKAGE_NAME_,verbose",
    "_R_CHECK_LICENSE_": "TRUE",
    "_R_CHECK_LIMIT_CORES_": "TRUE",
    "_R_CHECK_NATIVE_ROUTINE_REGISTRATION_": "TRUE",
    "_R_CHECK_NO_RECOMMENDED_": "TRUE",
    "_R_CHECK_NO_STOP_ON_TEST_ERROR_": "TRUE",
    "_R_CHECK_ORPHANED_": "TRUE",
    "_R_CHECK_PACKAGE_DATASETS_SUPPRESS_NOTES_": "TRUE",
    "_R_CHECK_PACKAGE_NAME_": "languageserver",
    "_R_CHECK_PACKAGES_USED_CRAN_INCOMING_NOTES_": "TRUE",
    "_R_CHECK_PACKAGES_USED_IGNORE_UNUSED_IMPORTS_": "TRUE",
    "_R_CHECK_PACKAGES_USED_IN_TESTS_USE_SUBDIRS_": "TRUE",
    "_R_CHECK_PRAGMAS_": "TRUE",
    "_R_CHECK_R_DEPENDS_": "warn",
    "_R_CHECK_R_ON_PATH_": "TRUE",
    "_R_CHECK_RD_CONTENTS_KEYWORDS_": "TRUE",
    "_R_CHECK_S3_METHODS_NOT_REGISTERED_": "TRUE",
    "_R_CHECK_SCREEN_DEVICE_": "stop",
    "_R_CHECK_SHLIB_OPENMP_FLAGS_": "TRUE",
    "_R_CHECK_SIZE_OF_TARBALL_": "76996",
    "_R_CHECK_SYSTEM_CLOCK_": "FALSE",
    "_R_CHECK_TIMINGS_": "10",
    "_R_OPTIONS_STRINGS_AS_FACTORS_": "FALSE",
    "_R_SHLIB_BUILD_OBJECTS_SYMBOL_TABLES_": "TRUE",
    "AGENT_TOOLSDIRECTORY": "/Users/runner/hostedtoolcache",
    "ANDROID_HOME": "/Users/runner/Library/Android/sdk",
    "ANDROID_NDK_18R_PATH": "/Users/runner/Library/Android/sdk/ndk/18.1.5063045",
    "ANDROID_NDK_HOME": "/Users/runner/Library/Android/sdk/ndk-bundle",
    "ANDROID_NDK_LATEST_HOME": "/Users/runner/Library/Android/sdk/ndk/22.1.7171670",
    "ANDROID_NDK_ROOT": "/Users/runner/Library/Android/sdk/ndk-bundle",
    "ANDROID_SDK_ROOT": "/Users/runner/Library/Android/sdk",
    "BIBINPUTS": ".:.:/Library/Frameworks/R.framework/Resources/share/texmf/bibtex/bib::/Library/Frameworks/R.framework/Resources/share/texmf/bibtex/bib:",
    "BOOTSTRAP_HASKELL_NONINTERACTIVE": "1",
    "BSTINPUTS": ".:.:/Library/Frameworks/R.framework/Resources/share/texmf/bibtex/bst::/Library/Frameworks/R.framework/Resources/share/texmf/bibtex/bst:",
    "CALLR_CHILD_R_LIBS": "/Users/runner/work/_temp/Library:/Library/Frameworks/R.framework/Versions/4.0/Resources/library",
    "CALLR_CHILD_R_LIBS_SITE": "",
    "CALLR_CHILD_R_LIBS_USER": "/Users/runner/work/_temp/Library:/Library/Frameworks/R.framework/Versions/4.0/Resources/library",
    "CALLR_R_LIBS_SITE_BAK": "",
    "CALLR_R_LIBS_USER_BAK": "/Users/runner/work/_temp/Library",
    "CALLR_R_PROFILE_USER_BAK": "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//Rtmp0SQM6a/file6112e988d6a",
    "CHROMEWEBDRIVER": "/usr/local/Caskroom/chromedriver/89.0.4389.23",
    "CI": "true",
    "CONDA": "/usr/local/miniconda",
    "CYGWIN": "nodosfilewarning",
    "DOTNET_MULTILEVEL_LOOKUP": "0",
    "DOTNET_ROOT": "/Users/runner/.dotnet",
    "DYLD_FALLBACK_LIBRARY_PATH": "/Library/Frameworks/R.framework/Resources/lib:/Users/runner/hostedtoolcache/Java_Adopt_jdk/8.0.282-8/x64/Contents/Home/lib/server",
    "EDGEWEBDRIVER": "/usr/local/share/edge_driver",
    "EDITOR": "vi",
    "GECKOWEBDRIVER": "/usr/local/opt/geckodriver/bin",
    "GITHUB_ACTION": "run2",
    "GITHUB_ACTION_REF": "",
    "GITHUB_ACTION_REPOSITORY": "",
    "GITHUB_ACTIONS": "true",
    "GITHUB_ACTOR": "randy3k",
    "GITHUB_API_URL": "https://api.github.com",
    "GITHUB_BASE_REF": "master",
    "GITHUB_ENV": "/Users/runner/work/_temp/_runner_file_commands/set_env_7a63375a-b33e-4c27-b9ca-0fcbf6b7ed99",
    "GITHUB_EVENT_NAME": "pull_request",
    "GITHUB_EVENT_PATH": "/Users/runner/work/_temp/_github_workflow/event.json",
    "GITHUB_GRAPHQL_URL": "https://api.github.com/graphql",
    "GITHUB_HEAD_REF": "release/0.3.10",
    "GITHUB_JOB": "macos",
    "GITHUB_PATH": "/Users/runner/work/_temp/_runner_file_commands/add_path_7a63375a-b33e-4c27-b9ca-0fcbf6b7ed99",
    "GITHUB_REF": "refs/pull/409/merge",
    "GITHUB_REPOSITORY": "REditorSupport/languageserver",
    "GITHUB_REPOSITORY_OWNER": "REditorSupport",
    "GITHUB_RETENTION_DAYS": "90",
    "GITHUB_RUN_ID": "762463588",
    "GITHUB_RUN_NUMBER": "1095",
    "GITHUB_SERVER_URL": "https://github.com",
    "GITHUB_SHA": "c05b77b5201ac9215beaa6ba6bd3e2c650752d9b",
    "GITHUB_WORKFLOW": "build",
    "GITHUB_WORKSPACE": "/Users/runner/work/languageserver/languageserver",
    "HOME": "/Users/runner",
    "HOMEBREW_CASK_OPTS": "--no-quarantine",
    "HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS": "3650",
    "HOMEBREW_NO_AUTO_UPDATE": "1",
    "ImageOS": "macos1015",
    "ImageVersion": "20210412.2",
    "JAVA_HOME": "/Users/runner/hostedtoolcache/Java_Adopt_jdk/8.0.282-8/x64/Contents/Home",
    "JAVA_HOME_11_X64": "/Users/runner/hostedtoolcache/Java_Adopt_jdk/11.0.10-9/x64/Contents/Home",
    "JAVA_HOME_12_X64": "/Users/runner/hostedtoolcache/Java_Adopt_jdk/12.0.2-10.3/x64/Contents/Home",
    "JAVA_HOME_13_X64": "/Users/runner/hostedtoolcache/Java_Adopt_jdk/13.0.2-8.1/x64/Contents/Home",
    "JAVA_HOME_14_X64": "/Users/runner/hostedtoolcache/Java_Adopt_jdk/14.0.2-12/x64/Contents/Home",
    "JAVA_HOME_8_X64": "/Users/runner/hostedtoolcache/Java_Adopt_jdk/8.0.282-8/x64/Contents/Home",
    "LANG": "en_US.UTF-8",
    "LANGUAGE": "en",
    "LC_ALL": "en_US.UTF-8",
    "LC_COLLATE": "C",
    "LC_CTYPE": "en_US.UTF-8",
    "LN_S": "ln -s",
    "LOGNAME": "runner",
    "MAKE": "make",
    "NOT_CRAN": "true",
    "NUNIT_BASE_PATH": "/Library/Developer/nunit",
    "NUNIT3_PATH": "/Library/Developer/nunit/3.6.0",
    "NVM_CD_FLAGS": "",
    "NVM_DIR": "/Users/runner/.nvm",
    "PAGER": "/usr/bin/less",
    "PATH": "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmp0SQM6a/file611633eb7d3/languageserver.Rcheck/R_check_bin:/usr/local/gfortran/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.5.1/x64",
    "PERFLOG_LOCATION_SETTING": "RUNNER_PERFLOG",
    "PIPX_BIN_DIR": "/usr/local/opt/pipx_bin",
    "PIPX_HOME": "/usr/local/opt/pipx",
    "POWERSHELL_DISTRIBUTION_CHANNEL": "GitHub-Actions-macos1015",
    "PROCESSX_PSDFDQRQLYEG_1618810954": "YES",
    "PROCESSX_PSZCQEWU3OVU_1618811543": "YES",
    "PWD": "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmp0SQM6a/file611633eb7d3/languageserver.Rcheck/tests/testthat",
    "R_ARCH": "",
    "R_BATCH": "",
    "R_BROWSER": "false",
    "R_BZIPCMD": "/usr/bin/bzip2",
    "R_CMD": "/Library/Frameworks/R.framework/Resources/bin/Rcmd",
    "R_DEFAULT_PACKAGES": "",
    "R_DOC_DIR": "/Library/Frameworks/R.framework/Resources/doc",
    "R_ENVIRON": "",
    "R_ENVIRON_USER": "",
    "R_GZIPCMD": "/usr/bin/gzip",
    "R_HOME": "/Library/Frameworks/R.framework/Resources",
    "R_INCLUDE_DIR": "/Library/Frameworks/R.framework/Resources/include",
    "R_LANGSVR_LOG": "/tmp/languageserver/macos-log",
    "R_LANGSVR_POOL_SIZE": "1",
    "R_LANGSVR_TEST_FAST": "NO",
    "R_LIBS": "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//Rtmpe5QjIW/RLIBS_63d598ba277",
    "R_LIBS_SITE": "no_such_dir",
    "R_LIBS_USER": "",
    "R_OSTYPE": "unix",
    "R_PAPERSIZE": "a4",
    "R_PAPERSIZE_USER": "a4",
    "R_PDFVIEWER": "false",
    "R_PLATFORM": "x86_64-apple-darwin17.0",
    "R_PRINTCMD": "lpr",
    "R_PROFILE": "",
    "R_PROFILE_USER": "",
    "R_QPDF": "/Library/Frameworks/R.framework/Resources/bin/qpdf",
    "R_RD4PDF": "times,inconsolata,hyper",
    "R_SESSION_TMPDIR": "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//Rtmpe5QjIW/working_dir/Rtmp7ZArZL",
    "R_SHARE_DIR": "/Library/Frameworks/R.framework/Resources/share",
    "R_STRIP_SHARED_LIB": "strip -x",
    "R_STRIP_STATIC_LIB": "strip -S",
    "R_SYSTEM_ABI": "macos,gcc,gxx,gfortran,gfortran",
    "R_TESTS": "",
    "R_TEXI2DVICMD": "/usr/local/bin/texi2dvi",
    "R_UNZIPCMD": "/usr/bin/unzip",
    "R_VERSION": "4.0.5",
    "R_ZIPCMD": "/usr/bin/zip",
    "RCT_NO_LAUNCH_PACKAGER": "1",
    "RSTUDIO_CONSOLE_WIDTH": "80",
    "RUNNER_OS": "macOS",
    "RUNNER_PERFLOG": "/usr/local/opt/runner/perflog",
    "RUNNER_TEMP": "/Users/runner/work/_temp",
    "RUNNER_TOOL_CACHE": "/Users/runner/hostedtoolcache",
    "RUNNER_TRACKING_ID": "github_77aa7d09-f663-4322-8bfa-0c202bb02997",
    "RUNNER_WORKSPACE": "/Users/runner/work/languageserver",
    "SED": "/usr/bin/sed",
    "SHELL": "/bin/bash",
    "SHLVL": "6",
    "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.hINarFBUn7/Listeners",
    "TAR": "/usr/bin/tar",
    "TESTTHAT": "true",
    "TESTTHAT_PKG": "languageserver",
    "TEXINPUTS": ".:.:/Library/Frameworks/R.framework/Resources/share/texmf/tex/latex::/Library/Frameworks/R.framework/Resources/share/texmf/tex/latex:",
    "TMPDIR": "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//Rtmpe5QjIW/working_dir",
    "TZ": "UTC",
    "USER": "runner",
    "VCPKG_INSTALLATION_ROOT": "/usr/local/share/vcpkg",
    "XCODE_10_DEVELOPER_DIR": "/Applications/Xcode_10.3.app/Contents/Developer",
    "XCODE_11_DEVELOPER_DIR": "/Applications/Xcode_11.7.app/Contents/Developer",
    "XCODE_12_DEVELOPER_DIR": "/Applications/Xcode_12.4.app/Contents/Developer",
    "XPC_FLAGS": "0x0",
    "XPC_SERVICE_NAME": "0"
  }
}
[2021-04-19 05:52:25.314] initialization config:  {
  "rootUri": "file:///var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//Rtmpe5QjIW/working_dir/Rtmp0hI9cO",
  "capabilities": null
}
[2021-04-19 05:52:28.124] deliver:  ["Response", "Message", "R6"]
[2021-04-19 05:52:29.500] received:  Content-Length: 40
[2021-04-19 05:52:29.533] received payload.
[2021-04-19 05:52:29.535] handling notification:  initialized
[2021-04-19 05:52:29.535] on_initialized
[2021-04-19 05:52:29.537] received:  Content-Length: 105
[2021-04-19 05:52:29.551] received payload.
[2021-04-19 05:52:29.552] handling notification:  workspace/didChangeConfiguration
[2021-04-19 05:52:29.553] settings  {
  "diagnostics": false
}
[2021-04-19 05:52:29.557] {
  "diagnostics": false
}
[2021-04-19 05:52:29.558] disable diagnostics
[2021-04-19 05:52:29.560] received:  Content-Length: 237
[2021-04-19 05:52:29.636] received payload.
[2021-04-19 05:52:29.640] handling notification:  textDocument/didSave
[2021-04-19 05:52:29.641] did save: {
  "uri": "file:///var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpe5QjIW/working_dir/Rtmp0hI9cO/file8806c53b4cc.R"
}
[2021-04-19 05:52:29.654] parse session acquired session_id = 1 remain pool size = 0
[2021-04-19 05:52:29.657] parse session ready 1 2021-04-19 05:52:29
[2021-04-19 05:52:29.664] received:  Content-Length: 342
[2021-04-19 05:52:29.738] received payload.
[2021-04-19 05:52:29.740] handling notification:  textDocument/didSave
[2021-04-19 05:52:29.741] did save: {
  "uri": "file:///var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpe5QjIW/working_dir/Rtmp0hI9cO/file8806b82f4a3.R"
}
[2021-04-19 05:52:29.778] received:  Content-Length: 239
[2021-04-19 05:52:29.831] received payload.
[2021-04-19 05:52:29.832] handling request:  textDocument/definition
[2021-04-19 05:52:29.836] token: {
  "full_token": "var",
  "right_token": "var",
  "package": null,
  "accessor": "",
  "token": "var"
}
[2021-04-19 05:52:29.838] guess namespace: stats
[2021-04-19 05:52:29.841] deliver:  ["Response", "Message", "R6"]
[2021-04-19 05:52:29.851] parse session released session_id = 1 remain pool size = 1
[2021-04-19 05:52:29.852] parse_callback called: {
  "uri": "file:///var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpe5QjIW/working_dir/Rtmp0hI9cO/file8806c53b4cc.R",
  "version": null
}
[2021-04-19 05:52:29.855] parse task timing: 0.201704025268555   file:///var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpe5QjIW/working_dir/Rtmp0hI9cO/file8806c53b4cc.R
[2021-04-19 05:52:30.071] parse session acquired session_id = 1 remain pool size = 0
[2021-04-19 05:52:30.094] received:  Content-Length: 239
[2021-04-19 05:52:30.144] received payload.
[2021-04-19 05:52:30.146] handling request:  textDocument/definition
[2021-04-19 05:52:30.213] token: {
  "full_token": "file8806c53b4cc.R",
  "right_token": "ile8806c53b4cc.R",
  "package": null,
  "accessor": "",
  "token": "file8806c53b4cc.R"
}
[2021-04-19 05:52:30.298] deliver:  ["Response", "Message", "R6"]
[2021-04-19 05:52:30.330] parse session released session_id = 1 remain pool size = 1
[2021-04-19 05:52:30.334] parse_callback called: {
  "uri": "file:///var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpe5QjIW/working_dir/Rtmp0hI9cO/file8806b82f4a3.R",
  "version": null
}
[2021-04-19 05:52:30.359] parse task timing: 0.617522954940796   file:///var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpe5QjIW/working_dir/Rtmp0hI9cO/file8806b82f4a3.R
[2021-04-19 05:52:30.662] resolve_callback called: {
  "uri": "file:///var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpe5QjIW/working_dir/Rtmp0hI9cO/file8806c53b4cc.R",
  "version": null
}
[2021-04-19 05:52:30.664] resolve task timing: 0.809977054595947   file:///var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpe5QjIW/working_dir/Rtmp0hI9cO/file8806c53b4cc.R
</details>

**Comment by randy3k** [comment]
Luckily, the CRAN submitted has rejected because of the unnecessary line for LazyData: https://github.com/REditorSupport/languageserver/pull/409/commits/a88d819ab6aca65c37bbc6a9c119f510dc76f8f4
So we would be able to include the fix in the next release.

**Comment by renkun-ken** [comment]
This is quite subtle but the cause of error immediately makes good sense! Thanks for digging into this!

**Pull request merged**
