### PR TITLE
Fix lintr output

### PR DESCRIPTION
**Pull request by Ikuyadeu**
Identify style or warning like RStudio output(https://github.com/jimhester/lintr#rstudio)

### CODE REVIEW

**Comment by randy3k** [comment]
Thank, it looks good.

**Comment by Ikuyadeu** [comment]
@randy3k OK, I'll fix but it's tomorrow.
By the way,
https://github.com/REditorSupport/languageserver/blob/5a072b687ba228b4d87d090b96fe42b973809d6d/R/diagnostics.R#L28
Should this line be `dianostics` to `diagnostics`?

**Comment by randy3k** [comment]
You are right.

**Comment by Ikuyadeu** [comment]
OK, fixed.

**Comment by randy3k** [comment]
Thanks

**Pull request merged**
